### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by lovipomidorku** [GooglyBlox/ClipboardToFileInput#2] opened 2023-11-27 10:20 UTC

**Comment by GooglyBlox** [comment] 2023-11-27 10:47
Hello! Would it be possible for you to send the links to the websites you're attempting it on?

**Comment by lovipomidorku** [comment] 2023-11-29 06:41
Hello. I'm using MacOS. I noticed such a problem when you copy a picture, for example, from Figma, then everything works. But when you copy an image file from finder or Telegram, it doesn't work anymore

**Comment by GooglyBlox** [comment] 2023-11-29 07:06
Oh, I haven't tested it on MacOS! Regardless, unfortunately, Chrome's permission schemes don't allow for the extension to handle clipboard items from the machine's system (like Finder). Those can (in most cases) probably just be dragged from your desktop or Finder to the file upload input anyway. The extension is only designed to handle items copied to the clipboard from the browser.

As for Telegram, I'll look into it!

**Comment by lovipomidorku** [comment] 2023-11-29 07:09
Unfortunately, not all sites support file dragging. Previously, I used Opera, but it is worse in performance than Chrome, so I returned to Chrome, but the easy-file function is very lacking(

**Comment by GooglyBlox** [comment] 2023-11-29 07:33
Unfortunately, I don't believe adding system file support would be possible (since extensions don't have access to your system files) :(

I took a look at Telegram, and I see what the issue is - I'll write up a fix ASAP.

**Comment by GooglyBlox** [comment] 2023-11-30 03:02
Hi! Quick follow-up before I start pushing commits. Did you mean the Telegram app or the Telegram website?

Copying from the Telegram app to pasting in a browser input field seems to work
And for Telegram web, you can paste files into the text box without needing to click the Photo/Video/File upload button

I'm probably misunderstanding, so I wanted to make sure just in case :)

**Comment by lovipomidorku** [comment] 2023-11-30 09:33
Hi! I mean Telegram Desktop App

**Comment by GooglyBlox** [comment] 2023-11-30 21:27
Hmm, I haven't been able to replicate the issue on Windows 10 - its looking like this may be a MacOS environment issue :(

I'll see if I can get my hands on a Mac device to see if there's anything that can be done to mitigate/resolve the issue. 👍

**Comment by lovipomidorku** [comment] 2023-12-01 07:29
Ok, thanks

**Comment by GooglyBlox** [comment] 2024-07-03 22:28
I don't really have any solution to this at the moment (and it may have simply resolved itself over the course of months of bug-fixes), so I'll close this issue for now. If there's any update on it later, it can be re-opened!

**Closed as not planned by GooglyBlox** 2024-07-03 22:28 UTC
